# Generated by Django 2.0.4 on 2021-11-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Full_Name',
        ),
    ]
